site_name: Signal Separation

# docs_dir: sources

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
  font:
    text: Roboto
    code: Roboto Mono

repo_name: tf2-ConvTasNet
repo_url: https://github.com/AiEngineering/tf2-ConvTasNet
edit_uri: ""

nav:
  - Overview: "index.md"
  - Foundations: "foundations.md"
  - Hyperparameters: "hyperparameters.md"
  - Data: "data.md"
  - Training: "training.md"
  - Persisting: "persisting.md"
  - TensorFlow: "tensorflow.md"
  - Source Code: "sources/sourcecode.md"
